disabled_rules:
- cyclomatic_complexity
- colon
- comma
- control_statement
- function_parameter_count
- trailing_whitespace

excluded:
- Pods
- xpocket/AppDelegate.swift

# configurated rules
file_length:
  warning: 500

function_body_length:
  warning: 50

identifier_name:
  allowed_symbols: ["_"]
  min_length: 1
  
line_length:
  warning: 200
  
type_body_length:
  warning: 270
  
custom_rules:
  open_iboutlets:
      included: ".*.swift"
      name: "IBOutlet opening"
      regex: '@IBOutlet ?(weak){0,1} var'
      message: "IBOutlet should be private"
      severity: warning

  open_ibaction:
      included: ".*.swift"
      name: "IBAction opening"
      regex: '@IBAction func'
      message: "IBAction should be private"
      severity: warning



